class_name WeaponResource
extends Resource

# Data-driven weapon definition (Phase 2 M3). Everything a weapon IS lives
# here — rig calibration, stow placement, stats — so adding a weapon means
# adding a resource, not code (CLAUDE.md: data-driven weapons).
#
# The .tres files in resources/weapons/ are GENERATED by tools/build_weapons.gd
# (the bake target for user calibration sessions). Never hand-edit them; edit
# the generator and re-run it, or the next rebuild silently reverts the change.
#
# The socket basis is stored as three COLUMN VECTORS, never a Transform3D
# literal: .tscn/.tres text serialises Transform3D column-wise, and a naive
# row-wise copy loads transposed (godot-scene-safety). Building the Basis
# from vectors in code sidesteps the trap entirely.

## Node name for the weapon's mesh instances and the WeaponManager's lookup key.
@export var id := &""
## Which animation set drives this weapon: the AnimationTree's WeaponBlend /
## FireClip / ReloadClip Blend2 amount. 0 = pistol set, 1 = rifle set.
@export var anim_set := 0
## The imported weapon FBX.
@export var mesh_scene: PackedScene

@export_group("Hand calibration")
## WeaponSocket basis columns on RightHandAttach. Calibrated ONCE per weapon —
## never per clip or stance; if it looks right in one animation and wrong in
## another, the bug is a missing Rest Fixer -> Overwrite Axis on import.
@export var socket_basis_x := Vector3.RIGHT
@export var socket_basis_y := Vector3.UP
@export var socket_basis_z := Vector3.BACK
@export var socket_origin := Vector3.ZERO
## The mesh's position under WeaponSocket — the origin-to-grip correction
## (weapon FBX origins sit mid-body, not at the grip).
@export var mesh_offset := Vector3.ZERO
## Where the support (left) palm belongs while AIMING, parented to the gun
## via SupportGrip so it stays valid in every clip. TwoBoneIK3D closes the
## reach gap.
@export var support_grip_pos := Vector3.ZERO
## Same, while CARRYING — a real support hand slides between two spots on
## the gun per stance (cradle near the receiver vs out on the foregrip).
## player.gd lerps SupportGrip between the two with the stance blend. For a
## carry that far-reaches ("left arm hyper extended" — user), pull this in
## toward the right hand.
@export var carry_support_grip_pos := Vector3.ZERO
## LeftElbowPole position — which way the left elbow points.
@export var elbow_pole_pos := Vector3.ZERO

@export_group("Support hand tuning")
## SupportHandTuner corrections on top of the mocap, per weapon: how wrong
## the source clip's left hand is on this rig holding THIS weapon.
@export var wrist_offset_deg := Vector3.ZERO
@export_range(-90.0, 90.0, 0.5) var thumb_curl := 0.0
@export_range(-90.0, 90.0, 0.5) var index_curl := 0.0
@export_range(-90.0, 90.0, 0.5) var middle_curl := 0.0
@export var curl_axis := Vector3(1, 0, 0)
@export var thumb_axis := Vector3(0.728, 0.0, 0.685)

@export_group("Stow")
## Which body socket carries the weapon while not equipped (Days Gone style:
## the non-equipped weapon stays visible, stowed on the body).
@export_enum("hip", "back") var stow_socket := "hip"
## Transform of the stow point (HipStow / BackStow node) on its BoneAttachment.
@export var stow_position := Vector3.ZERO
@export var stow_rotation_deg := Vector3.ZERO

@export_group("Animation")
## One-shot clip names in the baked library, consumed by build_anim_tree.gd
## (the FireClip/ReloadClip pickers are built from these, ordered by anim_set)
## and by the WeaponManager (reload clip length -> ReloadScale sync).
@export var fire_clip := &""
@export var reload_clip := &""

@export_group("Stats")
@export var damage := 0.0
## Rounds per minute; the fire-rate gate for M4.
@export var rpm := 0.0
@export var auto_fire := false
@export var mag_size := 0
@export var reserve := 0
@export var reload_time := 0.0
@export var spread_deg := 0.0
@export var recoil_pitch_deg := 0.0
@export var ads_fov := 42.0
@export var hitscan_range := 100.0
## Muzzle point in MESH space (measured off the barrel vertices) — M4 anchors
## muzzle flash / tracers here.
@export var muzzle_offset := Vector3.ZERO


func socket_transform() -> Transform3D:
	return Transform3D(Basis(socket_basis_x, socket_basis_y, socket_basis_z), socket_origin)


func stow_transform() -> Transform3D:
	return Transform3D(Basis.from_euler(stow_rotation_deg * (PI / 180.0)), stow_position)
