extends SceneTree

# Builds a usable Hunter_Male_01 character scene out of the shared Synty
# Characters.fbx, plus a small test level you can press F5 on.
#
# !! THIS OVERWRITES scenes/characters/hunter.tscn AND scenes/test_character.tscn.
# Every hand-tuned value in those scenes is mirrored in the constants below or
# in the WeaponResource files (weapon calibration lives in
# tools/build_weapons.gd -> resources/weapons/*.tres since M3), so a rebuild
# reproduces them. If you tune something in the editor, bake it back into the
# right generator or the next rebuild silently reverts it.
#
# Run with the editor CLOSED (after tools/build_weapons.gd if weapons changed):
#   /Applications/Godot.app/Contents/MacOS/Godot --headless --path . \
#       --script tools/build_character.gd
#
# WHY THIS EXISTS: Characters.fbx packs 31 character meshes onto ONE shared
# skeleton, and the material baked into the FBX is `Chr:BloodDecal11`, pointing
# at a `Blood_Decal.tga` that does not exist anywhere in the pack. Synty's real
# material assignment lives in Unity .mat/.meta GUID references that Godot
# cannot read. So we keep the one mesh we want and assign the atlas ourselves.
#
# Synty shading is deliberately flat: one albedo atlas, no metallic, low
# roughness spec. Do not add PBR maps that the art style does not use.

# Preloaded (not the global class name): a headless --script run does not
# rebuild the global class cache, so a fresh checkout would fail to resolve
# the class_name here.
const WeaponResource := preload("res://scripts/weapons/weapon_resource.gd")

const SRC := "res://assets/characters/Characters.fbx"
const ATLAS := "res://assets/textures/PolygonApocalypse_Texture_01_A.png"
const KEEP := "SM_Chr_Hunter_Male_01"

# Every dir here feeds the character's AnimationPlayer. pistol + rifle_mco are
# MotusMan-rig clips (MoCap Online); rifle / pistol_extra / unarmed are Mixamo
# X Bot clips; ual is Quaternius' CC0 library (one GLB, ~43 clips — `allow`
# picks the ones we use, `prefix` marks provenance). All arrive speaking
# humanoid-profile bone names via their BoneMaps
# (tools/rig/configure_imports.gd), so they coexist in one library.
const ANIM_DIRS := [
	{"dir": "res://assets/animations/pistol"},
	{"dir": "res://assets/animations/rifle_mco"},
	{"dir": "res://assets/animations/rifle"},
	{"dir": "res://assets/animations/pistol_extra"},
	{"dir": "res://assets/animations/unarmed"},
	{
		"dir": "res://assets/animations/ual",
		"prefix": "UAL_",
		"allow":
		[
			"Idle",
			"Walk",
			"Jog_Fwd",
			"Sprint",
			"Roll",
			"Pistol_Idle",
			"Pistol_Shoot",
			"Pistol_Reload",
			"Pistol_Aim_Up",
			"Pistol_Aim_Neutral",
			"Pistol_Aim_Down",
		],
	},
]
# Which weapon the SAVED scenes ship equipped and posed for — the pose
# autoplays so the calibration scene (test_character.tscn, F6, orbit
# camera) shows the right weapon in a real hold instead of a T-pose. The
# GAME is unaffected: the WeaponManager always re-applies its slot 0
# (revolver) plus visibility on startup. Flip to 1 + rebuild for a rifle
# hand-calibration session, back to 0 for pistol work.
const EQUIPPED_DEFAULT := 1
const DEFAULT_ANIMS := ["W1_Stand_Aim_Idle_IPC", "W2_Stand_Aim_Idle_v2"]
const FINGER_TIP_SCRIPT := "res://scripts/rig/finger_tip_modifier.gd"
const SUPPORT_TUNER_SCRIPT := "res://scripts/rig/support_hand_tuner.gd"

# Weapon calibration + stow placement is data-driven since M3: generated by
# tools/build_weapons.gd, consumed here (scene build) and by the
# WeaponManager (runtime switching). Order matters — slot order matches the
# weapon_1/weapon_2 input actions; EQUIPPED_DEFAULT above picks which one
# the saved calibration scenes pose.
const WEAPON_RES := [
	"res://resources/weapons/revolver.tres",
	"res://resources/weapons/assault_rifle.tres",
]
# Which bone each stow point rides on (Days Gone body carry). The stow NODE
# transform comes from each weapon's .tres.
const STOW_SOCKETS := {
	"hip": {"attach": "HipSocket", "bone": "Hips", "node": "HipStow"},
	"back": {"attach": "BackSocket", "bone": "UpperChest", "node": "BackStow"},
}

const OUT_CHAR := "res://scenes/characters/hunter.tscn"
const OUT_TEST := "res://scenes/test_character.tscn"
# The baked clip library, saved OUTSIDE the scene (issue #10): inlining every
# clip as .tscn sub-resources made hunter.tscn a ~14k-line text file that was
# rewritten wholesale on every rebuild and invisible to LFS. Binary .res, with
# its own explicit LFS entry in .gitattributes.
const LIB_OUT := "res://resources/animation/hunter_anim_library.res"

# The MoCap Online free demo pack's W2_ rifle FBXs carry a broken bind pose:
# their skeleton rests with hips at 0.506 m while the animation keys sit at
# ~1.70 m (the pistol pack is consistent: 0.941 rest vs 1.011 keys). The
# importer's normalize_position_tracks trusts the rest pose, silently skips
# scaling, and the clips play ~0.8 m in the air. MEASURED correction
# (2026-07-21, live against the pistol clips as ground truth):
#   * scale all position tracks by 1.011/1.695 = 0.596 (the two packs'
#     matching stand-aim-idle hips keys), then
#   * drop the hips track by 0.115 m — after scaling, every W2 clip's lowest
#     foot still hovered uniformly at ~0.17 m vs the pistol baseline's ~0.05.
# Verified on screen: feet plant identically to the pistol set.
const W2_POSITION_SCALE := 0.596
const W2_HIPS_Y_OFFSET := -0.115

# The W2 stand/aim clips lean the whole spine forward against the
# user-approved baselines (measured head-vs-hips lean, 2026-07-23: relaxed
# idle +5.2 deg vs U_Idle -4.4; aim idle +14.7 and walk-aim +14.0 vs the
# approved W1 pistol aim +5.0 — user: "leaning forward weirdly with the
# rifle"). Correction per CLIP, baked onto the spine-chain keys exactly like
# the UAL family fix; values calibrated by re-measuring after the bake.
# Gait clips are deliberately NOT corrected: UAL_Jog_Fwd leans +16.8 and
# passed review — jogging leans forward.
# Calibrated in two measured rounds: the head-vs-hips lean responds at
# ~0.59x the baked spine total (lever share of the chain above each joint).
# Target hit: relaxed idle lands at -2.9 (vs the approved U_Idle -4.4).
# The AIM clips are deliberately NOT corrected: leveling the aim spine
# rotates the gun up with it — a -16.5 bias on W2_Stand_Aim_Idle_v2 read as
# the rifle pointing ~35 deg skyward in ADS (screenshot-verified), while the
# clip's own +14.7 forward lean reads as an aim stance, not a defect.
const W2_POSTURE := {
	"W2_Stand_Relaxed_Idle_v2": -14.0,
}

# The Mixamo aim strafes hold their HIPS pitched back vs the aim idle, and
# hips are deliberately unfiltered in the RifleAim composite (legs live
# there) — so the whole aim upper body rode the lean and the gun measured a
# CONSTANT +8.4 deg muzzle-up across the strafe gait (probed in the running
# game, 2026-07-23; user: "not aiming straightforward" on A/D). Bias the
# hips pitch forward and counter-rotate both upper legs by the exact
# conjugate so the legs' world pose — and the foot plants — are unchanged.
# Calibrated by probe: the underlying hips delta vs the aim idle is ~21
# deg, but TorsoLookAt re-tracks ~60% of it, so the gun responds at ~0.35x
# the bias (8.4 -> gun 5.5; 14 -> gun ~2.8). Full correction would tip the
# pelvis visibly — 14 leaves a ~3 deg residual the LookAt hides in motion.
const STRAFE_HIPS_PITCH := {
	"R_Aim_Strafe_L": 14.0,
	"R_Aim_Strafe_R": 14.0,
}

# The Quaternius locomotion cycles read more theatrical than the Days Gone
# reference gait the user pointed at. Three measured compressions, all
# "scale deviation around the track's own mean" (character preserved, motion
# tightened), tuned across user reviews:
#   * hips bounce: vertical 0.35, lateral 0.7 ("going up and down" — fixed)
#   * stride width: leg rotations 0.75 ("the step itself is too wide")
#   * shoulder sway: spine-chain + clavicle rotations 0.5 ("shoulders heavily
#     going left and right")
#   * left-arm swing: 0.7, keeps the free hand from crossing the body.
const UAL_BOB_CLIPS := ["UAL_Walk", "UAL_Jog_Fwd", "UAL_Sprint"]
const UAL_BOB_Y_SCALE := 0.35
const UAL_BOB_XZ_SCALE := 0.7
const UAL_STRIDE_SCALE := 0.75
const UAL_STRIDE_BONES := ["LeftUpperLeg", "RightUpperLeg", "LeftLowerLeg", "RightLowerLeg"]
const UAL_SWAY_SCALE := 0.5
const UAL_SWAY_BONES := ["Spine", "Chest", "UpperChest", "LeftShoulder", "RightShoulder"]
const UAL_ARM_SCALE := 0.7
const UAL_ARM_BONES := ["LeftUpperArm", "LeftLowerArm"]
# "the head going right and left while jogging ... should be something like
# [ADS]: doesn't move or some slight move" — near-freeze it.
const UAL_HEAD_SCALE := 0.3
const UAL_HEAD_BONES := ["Neck", "Head"]

# Posture bias for the UAL clip family (negative = lean back / straighten
# the mocap hunch). The Quaternius rig holds a forward hunch — head pitched
# ~30 deg DOWN, measured — so the correction is BAKED into the UAL_* clips'
# spine-chain keys at build time. It must NOT be a runtime skeleton-wide
# modifier: that applied the same fix to every clip and pitched the
# level-headed U_Idle carry ~11 deg skyward (user-flagged; attributed by
# post-modifier probe A/B in the running game). PostureAdjust stays in the
# scene ZEROED as a live-tuning override only.
const POSTURE_SPINE_PITCH := -3.0
const POSTURE_CHEST_PITCH := -4.0
const POSTURE_UPPER_CHEST_PITCH := -4.0
# Was 8.0 as an anti-clipping bias; obsolete once the carry-time IK release
# fixed the real clipping cause, and it read as "hand way too far from the
# body" (user). Neutral now; the slider stays for live tuning if needed.
const POSTURE_RIGHT_ARM_OUT := 0.0


# Reduce locomotion bob: scale each hips position component's deviation from
# its own mean. Keeps the gait's character, shrinks the bounce.
func _reduce_bob(anim: Animation) -> void:
	for t in anim.get_track_count():
		if anim.track_get_type(t) != Animation.TYPE_POSITION_3D:
			continue
		if not String(anim.track_get_path(t)).ends_with(":Hips"):
			continue
		var n := anim.track_get_key_count(t)
		if n == 0:
			continue
		var mean := Vector3.ZERO
		for k in n:
			mean += anim.track_get_key_value(t, k) as Vector3
		mean /= float(n)
		for k in n:
			var v: Vector3 = anim.track_get_key_value(t, k)
			v.x = mean.x + (v.x - mean.x) * UAL_BOB_XZ_SCALE
			v.z = mean.z + (v.z - mean.z) * UAL_BOB_XZ_SCALE
			v.y = mean.y + (v.y - mean.y) * UAL_BOB_Y_SCALE
			anim.track_set_key_value(t, k, v)
	_compress_rotation(anim, UAL_STRIDE_BONES, UAL_STRIDE_SCALE)
	_compress_rotation(anim, UAL_SWAY_BONES, UAL_SWAY_SCALE)
	_compress_rotation(anim, UAL_ARM_BONES, UAL_ARM_SCALE)
	_compress_rotation(anim, UAL_HEAD_BONES, UAL_HEAD_SCALE)


# Bake the UAL posture correction into a clip: premultiply a constant pitch
# onto every spine-chain rotation key. Same math as the PostureAdjust
# modifier (Quaternion(RIGHT, rad) * pose), and left-multiplication commutes
# with blending, so mixes against unbaked clips fade the correction smoothly.
func _apply_posture_bias(anim: Animation) -> void:
	var bias := {
		"Spine": POSTURE_SPINE_PITCH,
		"Chest": POSTURE_CHEST_PITCH,
		"UpperChest": POSTURE_UPPER_CHEST_PITCH,
	}
	for t in anim.get_track_count():
		if anim.track_get_type(t) != Animation.TYPE_ROTATION_3D:
			continue
		var bone := String(anim.track_get_path(t)).get_slice(":", 1)
		if not bias.has(bone):
			continue
		var q := Quaternion(Vector3.RIGHT, deg_to_rad(bias[bone]))
		for k in anim.track_get_key_count(t):
			var rot: Quaternion = anim.track_get_key_value(t, k)
			anim.track_set_key_value(t, k, q * rot)


# Rotate a clip's hips pitch while preserving the legs' WORLD pose: the
# upper legs are children of the hips, so each leg key gets the exact
# conjugate correction (leg' = h^-1 q^-1 h leg, with h the hips rotation at
# that key's time). Legs are corrected FIRST, while the hips track still
# holds its original values to interpolate against.
func _apply_hips_pitch_bias(anim: Animation, deg: float) -> void:
	var q := Quaternion(Vector3.RIGHT, deg_to_rad(deg))
	var hips_rot := -1
	for t in anim.get_track_count():
		if (
			anim.track_get_type(t) == Animation.TYPE_ROTATION_3D
			and String(anim.track_get_path(t)).ends_with(":Hips")
		):
			hips_rot = t
	if hips_rot == -1:
		return
	for t in anim.get_track_count():
		if anim.track_get_type(t) != Animation.TYPE_ROTATION_3D:
			continue
		var bone := String(anim.track_get_path(t)).get_slice(":", 1)
		if bone != "LeftUpperLeg" and bone != "RightUpperLeg":
			continue
		for k in anim.track_get_key_count(t):
			var h := anim.rotation_track_interpolate(hips_rot, anim.track_get_key_time(t, k))
			var leg: Quaternion = anim.track_get_key_value(t, k)
			anim.track_set_key_value(t, k, h.inverse() * q.inverse() * h * leg)
	for k in anim.track_get_key_count(hips_rot):
		var rot: Quaternion = anim.track_get_key_value(hips_rot, k)
		anim.track_set_key_value(hips_rot, k, q * rot)


# Bake a total spine-chain pitch onto one clip, split evenly across the
# three spine segments (same left-multiplication as _apply_posture_bias, so
# it commutes with blending against uncorrected clips).
func _apply_pitch_bias(anim: Animation, total_deg: float) -> void:
	var per := total_deg / 3.0
	var bias := {"Spine": per, "Chest": per, "UpperChest": per}
	for t in anim.get_track_count():
		if anim.track_get_type(t) != Animation.TYPE_ROTATION_3D:
			continue
		var bone := String(anim.track_get_path(t)).get_slice(":", 1)
		if not bias.has(bone):
			continue
		var q := Quaternion(Vector3.RIGHT, deg_to_rad(bias[bone]))
		for k in anim.track_get_key_count(t):
			var rot: Quaternion = anim.track_get_key_value(t, k)
			anim.track_set_key_value(t, k, q * rot)


# Scale a rotation track's swing around its own mean orientation: for each
# key, slerp from the track mean toward the key by `scale`. 1.0 = untouched,
# 0.0 = frozen at the mean. The mean of nearby unit quaternions is the
# normalised component average (valid because a gait cycle stays well within
# one hemisphere).
func _compress_rotation(anim: Animation, bones: Array, scale: float) -> void:
	for t in anim.get_track_count():
		if anim.track_get_type(t) != Animation.TYPE_ROTATION_3D:
			continue
		var bone := String(anim.track_get_path(t)).get_slice(":", 1)
		if not bone in bones:
			continue
		var n := anim.track_get_key_count(t)
		if n < 2:
			continue
		var first: Quaternion = anim.track_get_key_value(t, 0)
		var acc := Vector4.ZERO
		for k in n:
			var q: Quaternion = anim.track_get_key_value(t, k)
			if q.dot(first) < 0.0:
				q = -q
			acc += Vector4(q.x, q.y, q.z, q.w)
		var mean := Quaternion(acc.x, acc.y, acc.z, acc.w).normalized()
		for k in n:
			var q2: Quaternion = anim.track_get_key_value(t, k)
			if q2.dot(mean) < 0.0:
				q2 = -q2
			anim.track_set_key_value(t, k, mean.slerp(q2, scale))


func _init() -> void:
	DirAccess.make_dir_recursive_absolute("res://scenes/characters")

	var ok := _build_character()
	if ok:
		ok = _build_test_level()
	quit(0 if ok else 1)


func _build_character() -> bool:
	var packed: PackedScene = load(SRC)
	if packed == null:
		push_error("cannot load " + SRC)
		return false
	var root: Node = packed.instantiate()

	var skel := _find_skeleton(root)
	if skel == null:
		push_error("no Skeleton3D in " + SRC)
		return false

	# Drop the 30 characters we are not using. They share the skeleton, so this
	# is purely removing MeshInstance3D siblings, not touching the rig.
	var removed := 0
	for child in skel.get_children():
		if child is MeshInstance3D and child.name != KEEP:
			skel.remove_child(child)
			child.queue_free()
			removed += 1

	var mesh := skel.get_node_or_null(NodePath(KEEP)) as MeshInstance3D
	if mesh == null:
		push_error("mesh %s not found under skeleton" % KEEP)
		return false

	var tex: Texture2D = load(ATLAS)
	if tex == null:
		push_error("cannot load atlas " + ATLAS)
		return false

	var mat := StandardMaterial3D.new()
	mat.albedo_texture = tex
	mat.metallic = 0.0
	mat.roughness = 0.9
	# Synty atlases are tiny colour swatches; smooth filtering bleeds
	# neighbouring swatches across UV seams. Nearest keeps colours crisp.
	mat.texture_filter = BaseMaterial3D.TEXTURE_FILTER_NEAREST
	# Assign as an override so it survives a re-import of the FBX.
	mesh.material_override = mat

	root.name = "Hunter"

	# Attach the retargeted MoCap clips. This only works because both rigs were
	# imported through BoneMaps, so the clips' track paths (%GeneralSkeleton:
	# LeftUpperArm ...) resolve against the Synty skeleton. Nothing is
	# retargeted at runtime.
	var anim_count := _attach_animations(root, skel)

	_own_all(root, root)

	var out := PackedScene.new()
	var err := out.pack(root)
	if err != OK:
		push_error("pack failed %d" % err)
		return false
	err = ResourceSaver.save(out, OUT_CHAR)

	var aabb := mesh.get_aabb()
	print("CHARACTER  removed_meshes=", removed)
	print("CHARACTER  bones=", skel.get_bone_count())
	print("CHARACTER  height_m=%.3f" % aabb.size.y)
	print("CHARACTER  atlas=", tex.resource_path, " ", tex.get_size())
	print("CHARACTER  animations=", anim_count)
	print("CHARACTER  saved=", OUT_CHAR, " err=", err)
	return err == OK


# Pulls every clip out of the imported animation FBXs into one AnimationPlayer
# on the character. DEFAULT_ANIM autoplays so the scene shows a real pose
# instead of the bind-pose T-pose.
func _attach_animations(root: Node, skel: Skeleton3D) -> int:
	# Track paths are authored against a uniquely-named skeleton node.
	skel.name = "GeneralSkeleton"
	skel.unique_name_in_owner = true

	# Characters.fbx ships its OWN AnimationPlayer holding a junk "Take 001"
	# clip. Leaving it in place means our player collides on name and gets
	# silently renamed to @AnimationPlayer@2, so anything looking up
	# "AnimationPlayer" finds the FBX's empty one instead of ours.
	for c in root.get_children():
		if c is AnimationPlayer:
			root.remove_child(c)
			c.queue_free()

	# Synty fingers have 4 joints; SkeletonProfileHumanoid defines only 3, so
	# the tips are never mapped and freeze in bind pose while the rest of the
	# finger curls. This modifier drives them from their parent joint.
	var tips := SkeletonModifier3D.new()
	tips.name = "FingerTips"
	tips.set_script(load(FINGER_TIP_SCRIPT))
	skel.add_child(tips)

	_attach_weapon(skel)

	var player := AnimationPlayer.new()
	player.name = "AnimationPlayer"
	var lib := AnimationLibrary.new()

	var count := 0
	for entry: Dictionary in ANIM_DIRS:
		var anim_dir: String = entry["dir"]
		var allow: Array = entry.get("allow", [])
		var prefix: String = entry.get("prefix", "")
		var d := DirAccess.open(anim_dir)
		if d == null:
			push_error("missing animation dir " + anim_dir)
			continue
		var files := d.get_files()
		files.sort()
		for f in files:
			if not f.get_extension().to_lower() in ["fbx", "glb"]:
				continue
			var ps: PackedScene = load(anim_dir.path_join(f))
			if ps == null:
				continue
			var inst: Node = ps.instantiate()
			var src := _find_anim_player(inst)
			if src == null:
				continue
			var clip_names: Array[String] = []
			for clip_name in src.get_animation_list():
				# "Take 001" is the junk bind-pose take skinned FBX exports
				# carry (same disease as Characters.fbx's own AnimationPlayer).
				if clip_name == "RESET" or clip_name == "Take 001":
					continue
				if not allow.is_empty() and not clip_name in allow:
					continue
				clip_names.append(clip_name)
			for clip_name in clip_names:
				var anim: Animation = src.get_animation(clip_name).duplicate(true)
				# Mixamo FBXs name their single take "mixamo.com"; key single-clip
				# files by filename so the library speaks our naming, not theirs.
				var key := clip_name
				if clip_names.size() == 1:
					key = f.get_basename()
				key = prefix + key
				if _should_loop(key):
					anim.loop_mode = Animation.LOOP_LINEAR
				if key.begins_with("W2_"):
					_fix_w2_positions(anim)
				_collapse_root_into_hips(anim)
				if key in UAL_BOB_CLIPS:
					_reduce_bob(anim)
				if key.begins_with("UAL_"):
					_apply_posture_bias(anim)
				if W2_POSTURE.has(key):
					_apply_pitch_bias(anim, W2_POSTURE[key])
				if STRAFE_HIPS_PITCH.has(key):
					_apply_hips_pitch_bias(anim, STRAFE_HIPS_PITCH[key])
				if lib.has_animation(key):
					push_error("duplicate clip name " + key + " from " + f)
					continue
				lib.add_animation(key, anim)
				count += 1
			inst.queue_free()

	# Save the library as its own binary resource and let the scene reference
	# it. take_over_path (NOT ResourceSaver.FLAG_CHANGE_PATH, which measurably
	# leaves resource_path empty in a headless SceneTree run) stamps the path
	# so the scene save externalises the library instead of inlining ~14k
	# lines of clip text into the .tscn.
	DirAccess.make_dir_recursive_absolute(LIB_OUT.get_base_dir())
	var lib_err := ResourceSaver.save(lib, LIB_OUT)
	if lib_err != OK:
		push_error("cannot save animation library %d" % lib_err)
		return 0
	lib.take_over_path(LIB_OUT)
	print("CHARACTER  anim_library=", LIB_OUT)

	player.add_animation_library("", lib)
	var default_anim: String = DEFAULT_ANIMS[EQUIPPED_DEFAULT]
	if lib.has_animation(default_anim):
		player.autoplay = default_anim
	root.add_child(player)
	return count


func _fix_w2_positions(anim: Animation) -> void:
	for t in anim.get_track_count():
		if anim.track_get_type(t) != Animation.TYPE_POSITION_3D:
			continue
		var is_hips := String(anim.track_get_path(t)).ends_with(":Hips")
		for k in anim.track_get_key_count(t):
			var v: Vector3 = anim.track_get_key_value(t, k) * W2_POSITION_SCALE
			if is_hips:
				v.y += W2_HIPS_Y_OFFSET
			anim.track_set_key_value(t, k, v)


# Some sources key the Root bone (the demo-pack W2 clips hold it at a constant
# -37 deg X; W1's D90/U90/Fire also carry Root tracks). A clip that keys Root
# POISONS every clip played after it that does not: AnimationPlayer leaves the
# bone at its last pose, so the whole character stays tilted — this produced
# the "everything after a rifle clip faces the sky" review round. In-place
# clips must not key Root at all, so compose Root's motion into the Hips
# tracks (global_hips = root * hips) and drop the Root tracks entirely.
func _collapse_root_into_hips(anim: Animation) -> void:
	var root_rot := -1
	var root_pos := -1
	var hips_rot := -1
	var hips_pos := -1
	for t in anim.get_track_count():
		var tp := String(anim.track_get_path(t))
		if tp.ends_with(":Root"):
			if anim.track_get_type(t) == Animation.TYPE_ROTATION_3D:
				root_rot = t
			elif anim.track_get_type(t) == Animation.TYPE_POSITION_3D:
				root_pos = t
		elif tp.ends_with(":Hips"):
			if anim.track_get_type(t) == Animation.TYPE_ROTATION_3D:
				hips_rot = t
			elif anim.track_get_type(t) == Animation.TYPE_POSITION_3D:
				hips_pos = t
	if root_rot == -1 and root_pos == -1:
		return
	if hips_rot != -1:
		for k in anim.track_get_key_count(hips_rot):
			var tm := anim.track_get_key_time(hips_rot, k)
			var rq := Quaternion.IDENTITY
			if root_rot != -1:
				rq = anim.rotation_track_interpolate(root_rot, tm)
			var hq: Quaternion = anim.track_get_key_value(hips_rot, k)
			anim.track_set_key_value(hips_rot, k, rq * hq)
	if hips_pos != -1:
		for k in anim.track_get_key_count(hips_pos):
			var tm := anim.track_get_key_time(hips_pos, k)
			var rq := Quaternion.IDENTITY
			if root_rot != -1:
				rq = anim.rotation_track_interpolate(root_rot, tm)
			var rp := Vector3.ZERO
			if root_pos != -1:
				rp = anim.position_track_interpolate(root_pos, tm)
			var hp: Vector3 = anim.track_get_key_value(hips_pos, k)
			anim.track_set_key_value(hips_pos, k, rq * hp + rp)
	for t in range(anim.get_track_count() - 1, -1, -1):
		if String(anim.track_get_path(t)).ends_with(":Root"):
			anim.remove_track(t)


# Stances and locomotion cycle; one-shots (fire, reload, draw/holster,
# transitions) do not. Filename-convention based, applied at build time.
func _should_loop(clip_key: String) -> bool:
	if clip_key.ends_with("_Loop_IPC") or clip_key.ends_with("_Idle_IPC"):
		return true
	for token: String in ["_Idle", "_Walk", "_Strafe", "_Jog", "_Loop", "_Sprint"]:
		if clip_key.contains(token):
			return true
	return false


# Engine-native weapon attachment: BoneAttachment3D -> calibrated socket ->
# weapon. No IK, no palm-socket math, no per-clip correction. The socket
# transform is calibrated ONCE per weapon and is valid for every clip,
# because import-time Overwrite Axis normalised the bone rest axes.
#
# All per-weapon values (socket basis, grip offsets, curls, stow placement)
# come from resources/weapons/*.tres — bake changes into build_weapons.gd.
# The saved scene ships with WEAPON_RES[0] equipped in the hand and every
# other weapon visible on its stow socket; at runtime the WeaponManager owns
# socket values and mesh visibility.
#
# override_pose stays OFF: the docs warn it interferes with the
# SkeletonModifier3D system, which we rely on for the fingertips, LookAt and
# TwoBoneIK.
func _attach_weapon(skel: Skeleton3D) -> void:
	var weapons: Array[WeaponResource] = []
	for path: String in WEAPON_RES:
		var w: WeaponResource = load(path)
		if w == null:
			push_error("weapon resource missing: %s — run tools/build_weapons.gd" % path)
			return
		weapons.append(w)
	var equipped: WeaponResource = weapons[EQUIPPED_DEFAULT]

	var att := BoneAttachment3D.new()
	att.name = "RightHandAttach"
	skel.add_child(att)
	att.bone_name = "RightHand"
	att.override_pose = false

	var socket := Node3D.new()
	socket.name = "WeaponSocket"
	att.add_child(socket)
	socket.transform = equipped.socket_transform()

	# Where the support palm belongs, riding with the gun so it stays valid in
	# every clip. Retargeting cannot fix limb-PROPORTION differences, so the
	# support hand lands ~19 cm from the grip on this rig; TwoBoneIK3D closes
	# that gap. Reach is 61 cm against ~50 cm needed, so it is never straining.
	# Position placed by the user on the gizmo, not computed.
	var support := Node3D.new()
	support.name = "SupportGrip"
	socket.add_child(support)
	support.position = equipped.support_grip_pos

	# The wrist correction as a DRAGGABLE control. It shipped as a Vector3
	# Inspector field, which made hand-tuning the palm roll "type three numbers,
	# look, type again" — the adjust-screenshot-adjust loop that the
	# user-places/Claude-plumbs split exists to prevent. Rotating a node with the
	# E gizmo is the interface now; SupportHandTuner reads this node's rotation
	# and mirrors the Euler back so the value is still readable and bakeable.
	# Parented under SupportGrip so it rides the gun, like every other calibrated
	# value here — set once per weapon, valid in every clip.
	var wrist := Node3D.new()
	wrist.name = "WristTarget"
	support.add_child(wrist)
	wrist.rotation_degrees = equipped.wrist_offset_deg

	# The GUN hand's roll. Parented to the SOCKET (not SupportGrip) because it
	# belongs to the hand holding the weapon, not to the support grip point.
	# Rotating it carries the gun with it — see the caution on
	# SupportHandTuner.right_wrist_target.
	var right_wrist := Node3D.new()
	right_wrist.name = "RightWristTarget"
	socket.add_child(right_wrist)
	right_wrist.rotation_degrees = equipped.right_wrist_offset_deg

	# Days Gone body carry: one stow point per body socket, its transform
	# owned by the weapon stowed there. The user drags HipStow / BackStow to
	# place; the values bake into build_weapons.gd.
	var stow_nodes := {}
	for key: String in STOW_SOCKETS:
		var cfg: Dictionary = STOW_SOCKETS[key]
		var stow_att := BoneAttachment3D.new()
		stow_att.name = cfg["attach"]
		skel.add_child(stow_att)
		stow_att.bone_name = cfg["bone"]
		stow_att.override_pose = false
		var stow := Node3D.new()
		stow.name = cfg["node"]
		stow_att.add_child(stow)
		stow_nodes[key] = stow

	# Two instances per weapon — hand + stowed, visibility-swapped at runtime
	# (no runtime reparenting). Saved state: WEAPON_RES[0] in the hand, the
	# rest stowed; the WeaponManager re-asserts this on _ready, so eye-icon
	# toggling during editor calibration sessions is safe.
	for w: WeaponResource in weapons:
		var hand := _instance_weapon(w)
		if hand == null:
			return
		socket.add_child(hand)
		hand.visible = w == equipped

		if not stow_nodes.has(w.stow_socket):
			push_error("unknown stow socket %s on %s" % [w.stow_socket, w.id])
			return
		var stow_node: Node3D = stow_nodes[w.stow_socket]
		stow_node.transform = w.stow_transform()
		var stowed := _instance_weapon(w)
		stow_node.add_child(stowed)
		stowed.visible = w != equipped

	# Posture override, live tuning ONLY — all pitches ship zeroed. The real
	# posture correction is baked per clip family (_apply_posture_bias on the
	# UAL_* clips); running it here skeleton-wide pitched the level U_Idle
	# carry skyward. The sliders remain so a tuning session can bias the spine
	# chain in the Remote tree without a rebuild.
	var posture := SkeletonModifier3D.new()
	posture.name = "PostureAdjust"
	posture.set_script(load("res://scripts/rig/posture_adjust.gd"))
	skel.add_child(posture)
	posture.set("spine_pitch_deg", 0.0)
	posture.set("chest_pitch_deg", 0.0)
	posture.set("upper_chest_pitch_deg", 0.0)
	posture.set("right_arm_out_deg", POSTURE_RIGHT_ARM_OUT)

	# Torso/head aim (Phase 2 M2). MUST run BEFORE LeftArmIK in child order so
	# the IK solves against the already-rotated torso (docs/rig-tuning.md).
	# forward_axis +Z is MEASURED: after Overwrite Axis every bone's global
	# rest basis is world-aligned and the character faces +Z. AimTarget is a
	# plain Node3D sibling of the skeleton; player.gd points it at the camera
	# ray while aiming and eases the modifiers' influence up/down.
	var aim_target := Node3D.new()
	aim_target.name = "AimTarget"
	skel.get_parent().add_child(aim_target)
	aim_target.position = Vector3(0, 1.4, 10.0)

	var torso_look := LookAtModifier3D.new()
	torso_look.name = "TorsoLookAt"
	skel.add_child(torso_look)
	torso_look.bone_name = "UpperChest"
	torso_look.target_node = NodePath("../../AimTarget")
	torso_look.forward_axis = SkeletonModifier3D.BONE_AXIS_PLUS_Z
	torso_look.primary_rotation_axis = Vector3.AXIS_Y
	torso_look.use_secondary_rotation = true
	torso_look.duration = 0.15
	torso_look.influence = 0.6

	var head_look := LookAtModifier3D.new()
	head_look.name = "HeadLookAt"
	skel.add_child(head_look)
	head_look.bone_name = "Head"
	head_look.target_node = NodePath("../../AimTarget")
	head_look.forward_axis = SkeletonModifier3D.BONE_AXIS_PLUS_Z
	head_look.primary_rotation_axis = Vector3.AXIS_Y
	head_look.use_secondary_rotation = true
	head_look.duration = 0.15
	head_look.influence = 0.35

	var ik := TwoBoneIK3D.new()
	ik.name = "LeftArmIK"
	skel.add_child(ik)
	ik.setting_count = 1
	ik.set_root_bone_name(0, "LeftUpperArm")
	ik.set_middle_bone_name(0, "LeftLowerArm")
	ik.set_end_bone_name(0, "LeftHand")
	ik.set_target_node(0, NodePath("../RightHandAttach/WeaponSocket/SupportGrip"))
	# Without a pole the elbow flips between valid solutions mid-animation.
	ik.set_pole_direction_vector(0, Vector3(0.0, -1.0, -0.35))
	ik.influence = 1.0

	# A draggable pole beats a hard-coded vector: the elbow can be aimed by
	# hand in the viewport instead of by editing numbers.
	var pole := Node3D.new()
	pole.name = "LeftElbowPole"
	skel.add_child(pole)
	pole.position = equipped.elbow_pole_pos
	ik.set_pole_node(0, NodePath("../LeftElbowPole"))

	# Wrist + finger corrections for the support hand. MUST be added AFTER the
	# IK: modifiers run top-to-bottom, so the IK places the arm and this
	# refines it. Ships all-zero, i.e. a no-op, so the pose is pure mocap
	# until someone authors a correction in the Inspector.
	var tuner := SkeletonModifier3D.new()
	tuner.name = "SupportHandTuner"
	tuner.set_script(load(SUPPORT_TUNER_SCRIPT))
	skel.add_child(tuner)
	# Corrections ON TOP of the mocap, per weapon ("how wrong the clip's left
	# hand is on this rig holding THIS gun") — the WeaponManager re-applies
	# them on every equip; the scene ships the default weapon's set.
	tuner.wrist_target = NodePath("../RightHandAttach/WeaponSocket/SupportGrip/WristTarget")
	tuner.wrist_offset_deg = equipped.wrist_offset_deg
	tuner.right_wrist_target = NodePath("../RightHandAttach/WeaponSocket/RightWristTarget")
	tuner.right_wrist_offset_deg = equipped.right_wrist_offset_deg
	tuner.right_thumb_curl = equipped.right_thumb_curl
	tuner.right_index_curl = equipped.right_index_curl
	tuner.right_middle_curl = equipped.right_middle_curl
	tuner.thumb_curl = equipped.thumb_curl
	tuner.index_curl = equipped.index_curl
	tuner.middle_curl = equipped.middle_curl
	tuner.curl_axis = equipped.curl_axis
	tuner.thumb_axis = equipped.thumb_axis


# One visual instance of a weapon: the imported FBX at its origin-to-grip
# offset (grip sits at the parent socket/stow origin), wearing the Synty
# atlas — the FBX's own material references a texture that does not exist.
func _instance_weapon(w: WeaponResource) -> Node3D:
	if w.mesh_scene == null:
		push_error("mesh scene missing on weapon " + String(w.id))
		return null
	var gun: Node3D = w.mesh_scene.instantiate()
	gun.name = String(w.id)
	gun.position = w.mesh_offset
	var gm := _find_mesh(gun)
	if gm != null:
		var gmat := StandardMaterial3D.new()
		gmat.albedo_texture = load(ATLAS)
		gmat.roughness = 0.8
		gmat.texture_filter = BaseMaterial3D.TEXTURE_FILTER_NEAREST
		gm.material_override = gmat
	return gun


func _find_mesh(n: Node) -> MeshInstance3D:
	if n is MeshInstance3D:
		return n
	for c in n.get_children():
		var r := _find_mesh(c)
		if r != null:
			return r
	return null


func _find_anim_player(n: Node) -> AnimationPlayer:
	if n is AnimationPlayer:
		return n
	for c in n.get_children():
		var r := _find_anim_player(c)
		if r != null:
			return r
	return null


func _build_test_level() -> bool:
	var root := Node3D.new()
	root.name = "TestCharacter"

	var ground := StaticBody3D.new()
	ground.name = "Ground"
	var gm := MeshInstance3D.new()
	gm.name = "Mesh"
	var plane := PlaneMesh.new()
	plane.size = Vector2(20, 20)
	var gmat := StandardMaterial3D.new()
	gmat.albedo_color = Color(0.22, 0.23, 0.25)
	plane.material = gmat
	gm.mesh = plane
	ground.add_child(gm)
	var col := CollisionShape3D.new()
	col.name = "Collision"
	var box := BoxShape3D.new()
	box.size = Vector3(20, 0.2, 20)
	col.shape = box
	col.position = Vector3(0, -0.1, 0)
	ground.add_child(col)
	root.add_child(ground)

	var char_scene: PackedScene = load(OUT_CHAR)
	if char_scene == null:
		push_error("cannot load " + OUT_CHAR)
		return false
	var hunter: Node = char_scene.instantiate()
	hunter.name = "Hunter"
	root.add_child(hunter)

	var cam := Camera3D.new()
	cam.name = "Camera3D"
	cam.position = Vector3(0, 1.2, 3.2)
	cam.rotation_degrees = Vector3(-6, 0, 0)
	root.add_child(cam)

	var sun := DirectionalLight3D.new()
	sun.name = "Sun"
	sun.rotation_degrees = Vector3(-45, -35, 0)
	sun.light_energy = 1.1
	sun.shadow_enabled = true
	root.add_child(sun)

	# Without an environment the viewport renders flat black in a built scene.
	var world := WorldEnvironment.new()
	world.name = "WorldEnvironment"
	var env := Environment.new()
	env.background_mode = Environment.BG_SKY
	env.sky = Sky.new()
	env.sky.sky_material = ProceduralSkyMaterial.new()
	env.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
	env.ambient_light_energy = 0.6
	world.environment = env
	root.add_child(world)

	_own_all(root, root)

	var out := PackedScene.new()
	var err := out.pack(root)
	if err != OK:
		push_error("pack failed %d" % err)
		return false
	err = ResourceSaver.save(out, OUT_TEST)
	print("TESTLEVEL  saved=", OUT_TEST, " err=", err)

	if err == OK:
		# Phase 2 owns the main scene (scenes/levels/test_range.tscn). Only
		# claim it if the project has none — a rebuild must never silently
		# repoint the game at the rig-calibration scene.
		var current: String = ProjectSettings.get_setting("application/run/main_scene", "")
		if current == "":
			ProjectSettings.set_setting("application/run/main_scene", OUT_TEST)
			var perr := ProjectSettings.save()
			print("TESTLEVEL  main_scene claimed, save err=", perr)
			return perr == OK
		print("TESTLEVEL  main_scene left as ", current)
		return true
	return false


# Nodes built in code have no owner, and PackedScene.pack() silently drops
# unowned children. Every node must be owned by the scene root.
#
# But do NOT recurse into an instanced sub-scene. A node with a
# scene_file_path is the root of its own packed scene; re-owning its children
# to OUR root makes pack() write them out a second time, so the scene ends up
# containing the character twice — the instanced copy plus a flattened,
# un-animated duplicate rendered on top of it. That looked exactly like the
# retarget having silently failed.
func _own_all(node: Node, owner_node: Node) -> void:
	for c in node.get_children():
		c.owner = owner_node
		if c.scene_file_path.is_empty():
			_own_all(c, owner_node)


func _find_skeleton(n: Node) -> Skeleton3D:
	if n is Skeleton3D:
		return n
	for c in n.get_children():
		var r := _find_skeleton(c)
		if r != null:
			return r
	return null
